### PR TITLE
Removed speed limiter for massive speedup in mouse mode

### PR DESCRIPTION
**Pull request by pyristix**
Pyautogui automatically puts in a 0.1 second delay after each function call. Removed it, got a massive speedup, and WOW the mouse is really fun to play with now.

### CODE REVIEW

**Comment by Pyristix** [comment]
Planning to add something before reopening the pull request

**Comment by Pyristix** [comment]
Added absolute mouse mode.

-Absolute mouse mode, instead of using an anchor, maps the space of your camera to the space of your screen.

-Just use the same actions as in anchorMouse mode. 

-By the way, to make sure you can reach the outer edges of the screen using this mode, I made it so that the screen is only mapped to the inner portions of the camera feed. I drew a picture below for clarity but you'll understand if you try it. 

image


-For now it only works with one monitor (Though nothing bad will happen if you have more than one connected).

-To select mouse mode, instead of doing "-m mouse", you have to choose between "-m absoluteMouse" and "-m anchorMouse". If you're reviewing this pull request, try checking out both of them since anchorMouse mode is much faster than before as well.

**Comment by Sofia-Ortega** [comment]
Wow it looks really good! I tested it and everything works beautifully. Only problem is that the code crashes when it reaches either the top or bottom left corner of my screen, but that can be taken care of in another pull request. I'll let Andrew take a look at your actual code to see if everything looks good. Other than that GREAT Job!!!!!

**Comment by Pyristix** [comment]
> Wow it looks really good! I tested it and everything works beautifully. Only problem is that the code crashes when it reaches either the top or bottom left corner of my screen, but that can be taken care of in another pull request. I'll let Andrew take a look at your actual code to see if everything looks good. Other than that GREAT Job!!!!!

Thank you! The crashing when you bring the mouse to a corner is actually a failsafe feature that's included in pyautogui so you have a way to easily stop the script when something goes wrong. We can remove it whenever we decide to. Thanks for looking at the request!!

**Review by andrew-fennell — APPROVED** [review]
Great!

**Pull request merged**
